[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
bitvec = "1.0.1"
fxhash = "0.2.1"
rayon = "1.10.0"
regex = "1.11.1"
smallvec = "1.13.2"
vector-map = "1.0.1"
